# yaml-language-server: $schema='none'.
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: parasol-insurance-app
  title: "Parasol Insurance App With ArgoCD and autmoated CI"
  description: Template to create all the neccesery objects and flows for the insurance application
  tags:
    - insurance
    - ai
    - vm
    - parasol
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Repository Information
      required:
        - repoName
        - githubOrgName
      properties:
        repoName:
          type: string
          title: Git Repository Name
          ui:autofocus: true
        githubOrgName:
          type: string
          title: GitHub Organization Name
          default: "Parasol_Organization"
          description: Parasol_Organization is our GitHub organization name
          
    - title: Component Information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          default: 'parasol-insurance-app'
          description: Unique name of the component. Expecting a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total.
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component (Group)
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: CI Information
      required:
        - registry
        - user
      properties:
        registry:
          title: Select an Image Registry
          type: string
          description: Image registry to store app images
          enum:
            - Quay
            - OpenShift Registry
          ui:options:
            enumNames:
              - "Quay"
              - "Openshift Registry"
        user:
          title: Username
          type: string
          description: Username to use
              
    - title: LLM Selector
      required:
        - resourcePicker
        - endpoint
      properties:
        resourcePicker:
          type: string
          title: "Select LLM to use for the app"
          description: "All availabe LLMs"
          enum:
            - GPT-NeoX
            - LLaMA (Meta)
            - Mistral
            - Alpaca
            - BLOOM
            - Falcon
        endpoint:
          type: string
          title: HTTP endpoint of the LLM model
              
    - title: Tags Selection
      properties:
        EntityTagsPicker:
          type: array
          ui:field: EntityTagsPicker
          ui:options:
            kinds: []
            showCounts: false
            helperText: Add Tags To The Application

  steps:
    - action: debug:wait
      id: git-repo-creation
      name: Git Repo Creation
      input:
        seconds: 1

    - action: debug:wait
      id: clone-template
      name: Clone Intelligent App Boilerplate
      input:
        seconds: 2

    - action: debug:wait
      id: wait-500
      name: Configure AI Models
      input:
        milliseconds: 500

    - action: debug:wait
      id: app-ci
      name: CI - Build and push image
      input:
        seconds: 5
        
    - action: debug:wait
      id: configure-llm
      name: Configure LLM endpoint
      input:
        seconds: 1

    - action: debug:wait
      id: gitops-configuration
      name: Prepare all ArgoCD objects and deploy
      input:
        seconds: 5

    - action: debug:wait
      id: sanity-checks
      name: Sanity Checks
      input:
        seconds: 3

  output:
    links:
      - title: Repository
        url: 'https://github.com/OpenShiftCommons2024/templates/tree/main/hello-world'
      - title: Open in catalog
        icon: catalog
        url: 'https://backstage-developer-hub-demo-project.apps.trtzhkmo.eastus.aroapp.io/catalog/default/component/dev-hub-test-demo'
