# yaml-language-server: $schema='none'.
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-fake-app
  title: "Create An Amazing App With VMs And Containers"
  description: Template to create an amazing OpenShift Commons Applciation - Recommanded!
  tags:
    - commons
    - ai
    - vm
spec:
  owner: ai_team
  type: service
  parameters:
    - title: Repository Information
      required:
        - repoName
        - githubOrgName
      properties:
        repoName:
          type: string
          title: Git Repository Name
        githubOrgName:
          type: string
          title: GitHub Organization Name
          const: "OpenShiftCommons2024"
          description: OpenShiftCommons2024 is our GitHub organization 
          
    - title: Component Information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          default: 'Parasol-AI-and-VM-app'
          description: Unique name of the component. Expecting a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total.
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component (Group)
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
              
    - title: LLM Selector
      properties:
        resourcePicker:
          type: string
          title: "Select LLM to use for the app"
          ui:field: EntityPicker
          ui:options:
            rows: 5
            kinds: ["Resource"]
            catalogFilter:
              "spec.type": "llm"
              
    - title: Tags Selection
      properties:
        EntityTagsPicker:
          type: array
          ui:field: EntityTagsPicker
          ui:options:
            kinds: []
            showCounts: false
            helperText: Add Tags To The Application

  steps:
    - action: debug:wait
      id: wait-300
      name: Git Repo Creation
      input:
        milliseconds: 300

    - action: debug:wait
      id: wait-600
      name: GitOps preperation
      input:
        milliseconds: 600

    - action: debug:wait
      id: wait-500
      name: Configure AI Models
      input:
        milliseconds: 500

    - action: debug:wait
      id: wait-400
      name: Deploy some more stuff
      input:
        milliseconds: 400
        
    - action: debug:wait
      id: wait-800
      name: Finish and check that all good
      input:
        milliseconds: 800

    - action: debug:wait
      id: wait-50
      name: DONE
      input:
        milliseconds: 50

  output:
    links:
      - title: Repository
        url: 'https://github.com/OpenShiftCommons2024/templates/tree/main/hello-world'
      - title: Open in catalog
        icon: catalog
        url: 'https://backstage-developer-hub-demo-project.apps.trtzhkmo.eastus.aroapp.io/catalog/default/component/dev-hub-test-demo'
