# yaml-language-server: $schema='none'.
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-fake-app
  title: "Create An Amazing App With VMs And Containers"
  description: Template to create an amazing commons app
  tags:
    - commons
    - ai
    - vm
spec:
  owner: ai_team
  type: service
  parameters:
    - title: Repository Information
      required:
        - repoName
        - githubOrgName
      properties:
        repoName:
          type: string
          title: Git Repository Name
        githubOrgName:
          type: string
          title: GitHub Organization Name
          default: OpenShiftCommons2024
          description: OpenShiftCommons2024 is the recommanded value
          
    - title: Component Information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component. Expecting a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total.
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component (Group)
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
              
    - title: EntityTagsPicker Example
    	properties:
    		EntityTagsPicker:
    			type: array
    			ui:field: EntityTagsPicker
    			ui:options:
    				kinds: []
    				showCounts: false
    				helperText: Add Tags To The Application
          
    - title: LLM selector
      required:
        - llm
      properties:
        llm:
          title: Name
          type: string
          description: LLM To be used for your application 
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - action: debug:wait
      id: wait-300
      name: Waiting for 300 milliseconds
      input:
        milliseconds: 300

    - action: debug:wait
      id: wait-600
      name: Waiting for 600 milliseconds
      input:
        milliseconds: 600

    - action: debug:wait
      id: wait-500
      name: Waiting for 500 milliseconds
      input:
        milliseconds: 500

    - action: debug:wait
      id: wait-400
      name: Waiting for 400 milliseconds
      input:
        milliseconds: 400
        
      - action: debug:wait
      id: wait-800
      name: Waiting for 800 milliseconds
      input:
        milliseconds: 800

    - action: debug:wait
      id: wait-100
      name: Waiting for 100 milliseconds
      input:
        milliseconds: 100
